[package]
name = "calculer"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Roy Wu"]
repository = "https://github.com/r9w/calculer"
description = """
Calculer -- CLI for SuanShu lib
"""
[dependencies]
